# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - cargo build -release
  arm64-linux:
    cmds: 
      # - cargo install cross
      - cross build --release --target aarch64-unknown-linux-musl
  amd64-linux:
    cmds: 
      # - cargo install cross
      - cross build --release --target x86_64-unknown-linux-musl
